refactor(script): Improve code readability and robustness
- Added comments to `spin_animation` and `kill_spin` for better understanding of their operations.
- Introduced error handling for `mktemp` to ensure the temporary file is created successfully, preventing potential failures.
- Applied minor whitespace and formatting adjustments for consistency and cleaner code.

Signed-off-by: tenfyzhong <tenfy@tenfy.cn>

diff --git a/aitag b/aitag
--- a/aitag
+++ b/aitag
@@ -40,20 +40,19 @@ spin_animation() {
     # Infinite loop to keep the animation running
     while true; do
         for i in "${spinner[@]}"; do
-            tput civis  # Hide the cursor to enhance the animation appearance
-            tput el1    # Clear the line from the cursor to the beginning to display the spinner
+            tput civis                                    # Hide the cursor to enhance the animation appearance
+            tput el1                                      # Clear the line from the cursor to the beginning to display the spinner
             printf "\r${YELLOW}%s${NC} %s..." "$i" "$msg" # Print the spinner and message
-            sleep 0.1   # Delay to control the speed of the animation
-            tput cub $(( ${#msg} + 5 )) # Move the cursor back to reset the spinner position
+            sleep 0.1                                     # Delay to control the speed of the animation
+            tput cub $((${#msg} + 5))                     # Move the cursor back to reset the spinner position
         done
     done
 }
 
-
 kill_spin() {
     if [ -n "$SPIN_PID" ]; then
         kill $SPIN_PID
-        wait $SPIN_PID 2>/dev/null  # Wait for the process to terminate and suppress error messages
+        wait $SPIN_PID 2>/dev/null # Wait for the process to terminate and suppress error messages
         SPIN_PID=
         printf "\n"
     fi
@@ -96,19 +95,19 @@ MODEL=${LLM_TAG_MODEL}
 
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        -h|--help)
+        -h | --help)
             show_help
             exit
             ;;
-        -a|--annotate)
+        -a | --annotate)
             TAG_OPTS+=("$1")
             shift
             ;;
-        -s|--sign)
+        -s | --sign)
             TAG_OPTS+=("$1")
             shift
             ;;
-        -u|--local-user)
+        -u | --local-user)
             TAG_OPTS+=("-u" "$2")
             shift 2
             ;;
@@ -173,10 +172,13 @@ SPIN_PID=$!
 MSG=$(echo "$DIFF" | llm -s "$(cat "$PROMPT")")
 kill_spin
 
-TEMP=$(mktemp)
-echo "$MSG" > "$TEMP"
+TEMP=$(mktemp -q)
+if [[ -z "$temp_file" || ! -f "$temp_file" ]]; then
+    echo "Error: Failed to create temporary file." >&2
+    exit 1
+fi
+echo "$MSG" >"$TEMP"
 ${EDITOR:-vi} "$TEMP"
-
 
 read -p "Create tag:$TAG_NAME with these details? [y/N] " confirm
 if [[ $confirm =~ ^[Yy]$ ]]; then
